from db.queries import artist as artist
from db.queries import card as card
from db.queries import combo as combo
from db.queries import illustration as illustration
from db.queries import image as image
from db.queries import legality as legality
from db.queries import price as price
from db.queries import related_token as related_token
from db.queries import rule as rule
from db.queries import sets as sets
