name: scheduled-job

on:
  schedule:
    - cron: '0 6 * * 3'
  workflow_dispatch:

jobs:
  cron:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update uv
        run: uv self update

      - name: Run main script
        run: uv run src/main.py
        env:
          IMAGES_DIR: ${{ secrets.IMAGES_DIR }}
          PSQL_URI: ${{ secrets.PSQL_URI }}
