name: images.yml
on:
  workflow_dispatch:

jobs:
  download:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Download images
        run: uv run src/tools/fetch_images.py
