name: migration

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run Migration
        run: uv run alembic upgrade head
        env:
          PSQL_URI: ${{ secrets.PSQL_URI }}
